Adiciona capacidade de alterar versão de documento com base em pacote
scieloorg/dsm pull request #65
Opened 2021-10-27 23:54 UTC by rafaelpezzuto

#### O que esse PR faz?
Adiciona um arcabouço que permite alterar os dados de um documento no site com base em uma versão de pacote.

#### Onde a revisão poderia começar?
Por commits

#### Como este poderia ser testado manualmente?
É preciso enviar pelo menos dois pacotes relacionados a um mesmo artigo. Depois, pode-se executar a nova funcionalidade para retornar o documento para uma versão anterior. Seguem as instruções:

```
python dsm/ingress.py upload_package ZIP_DA_VERSAO_1
python dsm/ingress.py upload_package ZIP_DA_VERSAO_2
python dsm/ingress.py change_document_version PID NUMERO_DA_VERSAO
```

Sugestão:

```
# busque um pacote que ainda não existe no article_files
# isso gerará um pacote em que version é 1
python dsm/ingress.py download_package KmHpPYrB3r77Nm7yzV68hZg

# faça alterações no zip coletado
# envie o zip coletado - o valor de version será 2
# e veja os dados alterados no site
python dsm/ingress.py upload_package ZIP_ALTERADO

# volte o documento no site para a versão 1 (e verifique no site que o conteúdo voltou a ser da version 1)
python dsm/ingress.py change_document_version PID 1
```

#### Algum cenário de contexto que queira dar?
N/A

### Screenshots
N/A

#### Quais são tickets relevantes?
N/A

### Referências
N/A

2021-11-09 00:35 UTC, rafaelpezzuto commented
@robertatakenaka Depois verifica se está de acordo com as correções que eu fiz.

2021-11-09 17:24 UTC, robertatakenaka commented on dsm/utils/files.py
> +        if prefix in file:
@rafaelpezzuto ausência de prefix pode significar que é o pdf original e não a tradução

2021-11-09 20:53 UTC, rafaelpezzuto commented on dsm/utils/files.py
> +        if prefix in file:
@robertatakenaka o prefix é obtido do XML (o nome do arquivo xml, sem a extensão).


`se ele é rendition o padrão do nome é {mesmo_nome_xml}.pdf e {mesmo_nome_xml}-{lang}.pdf`

aqui, `{mesmo_nome_xml}` é justamente o prefixo, independentemente se é tradução ou original.

2021-11-09 21:01 UTC, robertatakenaka commented on dsm/utils/files.py
> +        if prefix in file:
@rafaelpezzuto mas suponha um pacote:

```
> 1812-9528-iics-19-02-78.xml
> 1812-9528-iics-19-02-78.pdf
> 1812-9528-iics-19-02-78-en.pdf
> 1812-9528-iics-19-02-78-suppl.pdf
```

https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/narr/regra-nomeacao.html#elemento-nomeia-especial-exemplo-1

2021-11-10 10:59 UTC, robertatakenaka commented on dsm/utils/files.py
> +def get_file_type(file_path, prefix, pdf_langs):
`type` não é um bom nome. Talvez `role` ou algo que indique função...

2021-11-10 11:55 UTC, rafaelpezzuto commented on dsm/utils/files.py
> +def get_file_type(file_path, prefix, pdf_langs):
@robertatakenaka melhorei o nome

2021-11-10 20:37 UTC, rafaelpezzuto commented on dsm/utils/files.py
> +def get_file_type(file_path, prefix, pdf_langs):
@robertatakenaka não encontrei o ponto que você indicou haver falha no return do método get_file_role.

2021-11-10 21:15 UTC, robertatakenaka requested changes

2021-11-10 22:54 UTC, rafaelpezzuto commented on dsm/utils/files.py
> +                return 'renditions'
@robertatakenaka ok. resolvido.

2021-11-11 12:18 UTC, robertatakenaka approved these changes

2021-11-11 12:26 UTC, merged

2021-11-11 12:26 UTC, rafaelpezzuto commented
@robertatakenaka há muitos testes falhando (por conta de refatorações que fizemos em outros PRs).

Acho esses problemas merecem um PR a parte.